version: "3"

services:
  go-app:
    container_name: go-app
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - go-app-network
    command: tail -f /dev/null
    volumes:
      - ./.:/go/src/app

  pg:
    image: postgres:12-alpine
    container_name: pg
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=example
    networks:
      - go-app-network

networks:
  go-app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.56.0/24
